=== aangelo-21/xml-dtd/clase.dtd
<!ELEMENT clase (informacion_general, profesores, estudiantes, horarios, materiales)>
<!ELEMENT informacion_general (codigo, nombre, descripcion, semestre)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT semestre (#PCDATA)>

<!ELEMENT profesores (profesor+)>
<!ELEMENT profesor (nombre, apellido, correo, especialidad)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT correo (#PCDATA)>
<!ELEMENT especialidad (#PCDATA)>

<!ELEMENT estudiantes (estudiante+)>
<!ELEMENT estudiante (nombre, apellido, matricula, calificaciones)>
<!ELEMENT matricula (#PCDATA)>
<!ELEMENT calificaciones (calificacion+)>
<!ELEMENT calificacion (evaluacion, nota)>
<!ELEMENT evaluacion (#PCDATA)>
<!ELEMENT nota (#PCDATA)>

<!ELEMENT horarios (horario+)>
<!ELEMENT horario (dia, hora_inicio, hora_fin, aula)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT hora_inicio (#PCDATA)>
<!ELEMENT hora_fin (#PCDATA)>
<!ELEMENT aula (#PCDATA)>

<!ELEMENT materiales (material+)>
<!ELEMENT material (titulo, tipo, link)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT link (#PCDATA)>

=== aangelo-21/xml-dtd/clase.xml
<!DOCTYPE clase SYSTEM "clase.dtd">
<clase>
    <informacion_general>
        <codigo>CS202</codigo>
        <nombre>Estructuras de Datos</nombre>
        <descripcion>Curso avanzado sobre estructuras de datos como listas, pilas y árboles.</descripcion>
        <semestre>2024-1</semestre>
    </informacion_general>
    
    <profesores>
        <profesor>
            <nombre>María</nombre>
            <apellido>Fernández</apellido>
            <correo>maria.fernandez@universidad.edu</correo>
            <especialidad>Algoritmos</especialidad>
        </profesor>
        <profesor>
            <nombre>Carlos</nombre>
            <apellido>Ruiz</apellido>
            <correo>carlos.ruiz@universidad.edu</correo>
            <especialidad>Programación</especialidad>
        </profesor>
    </profesores>
    
    <estudiantes>
        <estudiante>
            <nombre>Lucía</nombre>
            <apellido>Pérez</apellido>
            <matricula>20230001</matricula>
            <calificaciones>
                <calificacion>
                    <evaluacion>Parcial 1</evaluacion>
                    <nota>85</nota>
                </calificacion>
                <calificacion>
                    <evaluacion>Parcial 2</evaluacion>
                    <nota>90</nota>
                </calificacion>
            </calificaciones>
        </estudiante>
        <estudiante>
            <nombre>Juan</nombre>
            <apellido>Martínez</apellido>
            <matricula>20230002</matricula>
            <calificaciones>
                <calificacion>
                    <evaluacion>Parcial 1</evaluacion>
                    <nota>78</nota>
                </calificacion>
                <calificacion>
                    <evaluacion>Parcial 2</evaluacion>
                    <nota>82</nota>
                </calificacion>
            </calificaciones>
        </estudiante>
    </estudiantes>
    
    <horarios>
        <horario>
            <dia>Lunes</dia>
            <hora_inicio>08:00</hora_inicio>
            <hora_fin>10:00</hora_fin>
            <aula>A101</aula>
        </horario>
        <horario>
            <dia>Miércoles</dia>
            <hora_inicio>08:00</hora_inicio>
            <hora_fin>10:00</hora_fin>
            <aula>A101</aula>
        </horario>
    </horarios>
    
    <materiales>
        <material>
            <titulo>Apuntes de Listas</titulo>
            <tipo>PDF</tipo>
            <link>https://universidad.edu/materiales/listas.pdf</link>
        </material>
        <material>
            <titulo>Ejercicios de Árboles</titulo>
            <tipo>Documento</tipo>
            <link>https://universidad.edu/materiales/arboles.docx</link>
        </material>
    </materiales>
</clase>
